name: Postman Test and Allure Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 18 * * 3' # Runs every Wednesday at 7:30pm
    - cron: '50 18 * * 5' # Runs every Friday at 7:30pm
    - cron: '0 20 * * 0' # Runs every Sunday at 8:00pm

jobs:
  run_tests:
    if: github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install newman and newman-reporter-allure
        run: |
          npm install -g newman newman-reporter-allure
          echo "Newman and newman-reporter-allure installed."
      - name: Run Postman tests
        if: always()
        continue-on-error: true
        run: |
           newman run Postmans-Collections/Postmans-Collections.json --reporters cli,allure
           echo "Postman tests run."
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy existing content to allure-history
        run: |
          mkdir -p allure-history
          if [ -d gh-pages ]; then
            cp -r gh-pages/* allure-history/
          fi
      - name: Find latest folder in gh-pages
        id: latest_folder
        run: |
          latest_folder=$(find gh-pages -mindepth 1 -maxdepth 1 -type d -name '[0-9]*' | sort -n | tail -n 1)
          echo "Latest Folder: $latest_folder"
          echo "::set-output name=latest_folder::$latest_folder"
      - name: Parse latest summary.json
        id: parse_json
        run: |
          summary_path="${{ steps.latest_folder.outputs.latest_folder }}/widgets/summary.json"
          echo "Summary Path: $summary_path"
          if [ -f "$summary_path" ]; then
            cat "$summary_path"
            passed_tests=$(jq -r '.statistic.passed' "$summary_path")
            failed_tests=$(jq -r '.statistic.failed' "$summary_path")
            total_tests=$((passed_tests + failed_tests))
            if [ "$total_tests" -gt 0 ]; then
              passing_percentage=$(( passed_tests * 100 / total_tests ))
              failing_percentage=$(( failed_tests * 100 / total_tests ))
            else
              passing_percentage=0
              failing_percentage=0
            fi
            echo "Passed Tests: $passed_tests"
            echo "Failed Tests: $failed_tests"
            echo "Passing Percentage: $passing_percentage%"
            echo "Failing Percentage: $failing_percentage%"
            echo "::set-output name=passing_percentage::$passing_percentage"
            echo "::set-output name=failing_percentage::$failing_percentage"
            echo "::set-output name=passed_tests::$passed_tests"
            echo "::set-output name=failed_tests::$failed_tests"
          else
            echo "summary.json not found"
            echo "::set-output name=passing_percentage::0"
            echo "::set-output name=failing_percentage::0"
            echo "::set-output name=passed_tests::0"
            echo "::set-output name=failed_tests::0"
          fi
      - name: Update Allure Report Widget Title
        continue-on-error: true
        if: steps.build.outcome == 'success'
        run: |
          latest_folder=${{ steps.latest_folder.outputs.latest_folder }}
          echo "Latest Folder: $latest_folder"
          summary_path="$latest_folder/widgets/summary.json"
          echo "Summary Path: $summary_path"
          if [[ -e "$summary_path" ]]; then
            cat "$summary_path"  # Print content before
            sudo sed -i 's/Allure Report/CrendlyCheck - API Quality Readiness/' "$summary_path"
            cat "$summary_path"  # Print content after
          else
            echo "Error: summary.json not found in the latest folder."
          fi
      - name: Allure report action
        id: build
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to GitHub Pages
        id: deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: Wait for Allure report to be generated
        if: always()
        continue-on-error: true
        run: sleep 10
      - name: Notify Slack
        if: github.event_name == 'schedule'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'C070KUKPDLZ'
          SLACK_MESSAGE: |
            *CrendlyCheck - API Quality Readiness*
            *Contributors - Wuraola*
            Status: ${{ job.status }}
            Passing Tests: ${{ steps.parse_json.outputs.passing_percentage }}%
            Failing Tests: ${{ steps.parse_json.outputs.failing_percentage }}%
            Total Passed: ${{ steps.parse_json.outputs.passed_tests }}
            Total Failed: ${{ steps.parse_json.outputs.failed_tests }}
            GitHub Pages URL: ${{ secrets.PAGES_URL }}
